//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSTester.DOXAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dmsdox.com/", ConfigurationName="DOXAPI.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string userName, string password, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetAllDocTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        DNSTester.DOXAPI.DocType[] GetAllDocTypes(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        DNSTester.DOXAPI.Document GetDocument(string token, DNSTester.DOXAPI.Document docToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetTreeItemWithDocType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        DNSTester.DOXAPI.TreeItemWithDocType GetTreeItemWithDocType(string token, DNSTester.DOXAPI.TreeItemWithDocType itemToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/UpdateTreeItemWithDocType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string UpdateTreeItemWithDocType(string token, DNSTester.DOXAPI.TreeItemWithDocType updateItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/DeleteDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string DeleteDocument(string token, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/Archive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string Archive(string token, DNSTester.DOXAPI.Document doc, DNSTester.DOXAPI.Binder binder, string dividerPath, bool ocr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/FindTreeItemWithDocType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        DNSTester.DOXAPI.TreeItemWithDocType[] FindTreeItemWithDocType(string token, DNSTester.DOXAPI.SearchField[] searchFields, long docTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetDocType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        DNSTester.DOXAPI.DocType GetDocType(string token, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/CreateBinder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string CreateBinder(string token, DNSTester.DOXAPI.Binder binder, string parentBranch, DNSTester.DOXAPI.DividerSet dividerSet);
        
        // CODEGEN: Parameter 'data' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        DNSTester.DOXAPI.UploadFileResponse UploadFile(DNSTester.DOXAPI.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/LoggenInUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string[] LoggenInUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetBarCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string[] GetBarCodes(string token, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/QuickBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string[] QuickBarCode(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetDocumentURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string GetDocumentURL(string token, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dmsdox.com/GetQueryURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Field[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DividerSet[]))]
        string GetQueryURL(string token, DNSTester.DOXAPI.SearchField[] searchFields, long docTypeId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class DocType : BasicObject {
        
        private long docTypeIdField;
        
        private string nameField;
        
        private string tableNameField;
        
        private bool tableCreatedField;
        
        private int childIdField;
        
        private string titleFieldField;
        
        private string dataUrlField;
        
        private string verificationUrlField;
        
        private string actionField;
        
        private DocTypeAttribute[] attributesField;
        
        private DividerSet[] dividerSetsField;
        
        private int[] groupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long DocTypeId {
            get {
                return this.docTypeIdField;
            }
            set {
                this.docTypeIdField = value;
                this.RaisePropertyChanged("DocTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool TableCreated {
            get {
                return this.tableCreatedField;
            }
            set {
                this.tableCreatedField = value;
                this.RaisePropertyChanged("TableCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ChildId {
            get {
                return this.childIdField;
            }
            set {
                this.childIdField = value;
                this.RaisePropertyChanged("ChildId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TitleField {
            get {
                return this.titleFieldField;
            }
            set {
                this.titleFieldField = value;
                this.RaisePropertyChanged("TitleField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DataUrl {
            get {
                return this.dataUrlField;
            }
            set {
                this.dataUrlField = value;
                this.RaisePropertyChanged("DataUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VerificationUrl {
            get {
                return this.verificationUrlField;
            }
            set {
                this.verificationUrlField = value;
                this.RaisePropertyChanged("VerificationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public DocTypeAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("Attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public DividerSet[] DividerSets {
            get {
                return this.dividerSetsField;
            }
            set {
                this.dividerSetsField = value;
                this.RaisePropertyChanged("DividerSets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public int[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
                this.RaisePropertyChanged("Groups");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class DocTypeAttribute : BasicObject {
        
        private int idField;
        
        private string nameField;
        
        private bool inSearchField;
        
        private bool enabledField;
        
        private int orderField;
        
        private string columnNameField;
        
        private string attribIdField;
        
        private DataTypes dTypeField;
        
        private string helpField;
        
        private string defaultValueField;
        
        private int commandHeightField;
        
        private bool defaultSearchField;
        
        private bool titleField;
        
        private bool systemFieldField;
        
        private int uniqueFieldValField;
        
        private int maxLengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool InSearch {
            get {
                return this.inSearchField;
            }
            set {
                this.inSearchField = value;
                this.RaisePropertyChanged("InSearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AttribId {
            get {
                return this.attribIdField;
            }
            set {
                this.attribIdField = value;
                this.RaisePropertyChanged("AttribId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public DataTypes DType {
            get {
                return this.dTypeField;
            }
            set {
                this.dTypeField = value;
                this.RaisePropertyChanged("DType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Help {
            get {
                return this.helpField;
            }
            set {
                this.helpField = value;
                this.RaisePropertyChanged("Help");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("DefaultValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int CommandHeight {
            get {
                return this.commandHeightField;
            }
            set {
                this.commandHeightField = value;
                this.RaisePropertyChanged("CommandHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool DefaultSearch {
            get {
                return this.defaultSearchField;
            }
            set {
                this.defaultSearchField = value;
                this.RaisePropertyChanged("DefaultSearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool SystemField {
            get {
                return this.systemFieldField;
            }
            set {
                this.systemFieldField = value;
                this.RaisePropertyChanged("SystemField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int UniqueFieldVal {
            get {
                return this.uniqueFieldValField;
            }
            set {
                this.uniqueFieldValField = value;
                this.RaisePropertyChanged("UniqueFieldVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
                this.RaisePropertyChanged("MaxLength");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public enum DataTypes {
        
        /// <remarks/>
        Alphanumeric,
        
        /// <remarks/>
        Numeric,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        YesNo,
        
        /// <remarks/>
        Lookup,
        
        /// <remarks/>
        Dlookup,
        
        /// <remarks/>
        NumValue,
        
        /// <remarks/>
        LinkField,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TreeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TreeItemWithDocType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Binder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Divider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DividerTemplate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DividerSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocTypeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public abstract partial class BasicObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private User userField;
        
        private long idField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public User User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class User : BasicObject {
        
        private string userNameField;
        
        private string fullNameField;
        
        private int loginIdField;
        
        private long idField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class SearchField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldNameField;
        
        private string fieldValueField;
        
        private SearchTypes searchTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldValue {
            get {
                return this.fieldValueField;
            }
            set {
                this.fieldValueField = value;
                this.RaisePropertyChanged("FieldValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SearchTypes SearchType {
            get {
                return this.searchTypeField;
            }
            set {
                this.searchTypeField = value;
                this.RaisePropertyChanged("SearchType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public enum SearchTypes {
        
        /// <remarks/>
        StartWith,
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Exact,
        
        /// <remarks/>
        RangeDate,
        
        /// <remarks/>
        RangeNumeric,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class Field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DocTypeAttribute attrField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocTypeAttribute Attr {
            get {
                return this.attrField;
            }
            set {
                this.attrField = value;
                this.RaisePropertyChanged("Attr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class DividerTemplate : BasicObject {
        
        private DocType docTypeField;
        
        private DividerSet setField;
        
        private bool docField;
        
        private DocType childDocTypeField;
        
        private DocType dividerDocTypeField;
        
        private bool defaultDocumentField;
        
        private Divider instanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocType DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DividerSet Set {
            get {
                return this.setField;
            }
            set {
                this.setField = value;
                this.RaisePropertyChanged("Set");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
                this.RaisePropertyChanged("Doc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DocType ChildDocType {
            get {
                return this.childDocTypeField;
            }
            set {
                this.childDocTypeField = value;
                this.RaisePropertyChanged("ChildDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DocType DividerDocType {
            get {
                return this.dividerDocTypeField;
            }
            set {
                this.dividerDocTypeField = value;
                this.RaisePropertyChanged("DividerDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool DefaultDocument {
            get {
                return this.defaultDocumentField;
            }
            set {
                this.defaultDocumentField = value;
                this.RaisePropertyChanged("DefaultDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Divider Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("Instance");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class DividerSet : BasicObject {
        
        private int setIdField;
        
        private DocType docTypeField;
        
        private string setNameField;
        
        private string setDescField;
        
        private DividerSet baseSetField;
        
        private bool isNewField;
        
        private int orderField;
        
        private DividerTemplate[] defaultDividersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SetId {
            get {
                return this.setIdField;
            }
            set {
                this.setIdField = value;
                this.RaisePropertyChanged("SetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DocType DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SetName {
            get {
                return this.setNameField;
            }
            set {
                this.setNameField = value;
                this.RaisePropertyChanged("SetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SetDesc {
            get {
                return this.setDescField;
            }
            set {
                this.setDescField = value;
                this.RaisePropertyChanged("SetDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DividerSet BaseSet {
            get {
                return this.baseSetField;
            }
            set {
                this.baseSetField = value;
                this.RaisePropertyChanged("BaseSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
                this.RaisePropertyChanged("IsNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public DividerTemplate[] DefaultDividers {
            get {
                return this.defaultDividersField;
            }
            set {
                this.defaultDividersField = value;
                this.RaisePropertyChanged("DefaultDividers");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class Divider : TreeItemWithDocType {
        
        private int partOrderField;
        
        private string partLetterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PartOrder {
            get {
                return this.partOrderField;
            }
            set {
                this.partOrderField = value;
                this.RaisePropertyChanged("PartOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PartLetter {
            get {
                return this.partLetterField;
            }
            set {
                this.partLetterField = value;
                this.RaisePropertyChanged("PartLetter");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Binder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Divider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class TreeItemWithDocType : TreeItem {
        
        private DocType docTypeField;
        
        private Field[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocType DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TreeItemWithDocType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Binder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Divider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Document))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class TreeItem : BasicObject {
        
        private TreeItem parentField;
        
        private TreeItemTypes itemTypeField;
        
        private int orderNumberField;
        
        private string titleField;
        
        private string subTitleField;
        
        private string uniqueKeyField;
        
        private System.DateTime insertedDateField;
        
        private System.DateTime updatedDateField;
        
        private long bookIdField;
        
        private string idPathField;
        
        private bool noFilesField;
        
        private bool defDivField;
        
        private TreeItem[] childrenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TreeItem Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
                this.RaisePropertyChanged("Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TreeItemTypes ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
                this.RaisePropertyChanged("ItemType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SubTitle {
            get {
                return this.subTitleField;
            }
            set {
                this.subTitleField = value;
                this.RaisePropertyChanged("SubTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UniqueKey {
            get {
                return this.uniqueKeyField;
            }
            set {
                this.uniqueKeyField = value;
                this.RaisePropertyChanged("UniqueKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime InsertedDate {
            get {
                return this.insertedDateField;
            }
            set {
                this.insertedDateField = value;
                this.RaisePropertyChanged("InsertedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime UpdatedDate {
            get {
                return this.updatedDateField;
            }
            set {
                this.updatedDateField = value;
                this.RaisePropertyChanged("UpdatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
                this.RaisePropertyChanged("BookId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IdPath {
            get {
                return this.idPathField;
            }
            set {
                this.idPathField = value;
                this.RaisePropertyChanged("IdPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool NoFiles {
            get {
                return this.noFilesField;
            }
            set {
                this.noFilesField = value;
                this.RaisePropertyChanged("NoFiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool DefDiv {
            get {
                return this.defDivField;
            }
            set {
                this.defDivField = value;
                this.RaisePropertyChanged("DefDiv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public TreeItem[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
                this.RaisePropertyChanged("Children");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public enum TreeItemTypes {
        
        /// <remarks/>
        Unavailable,
        
        /// <remarks/>
        Branch,
        
        /// <remarks/>
        Binder,
        
        /// <remarks/>
        Divider,
        
        /// <remarks/>
        Document,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class Binder : TreeItemWithDocType {
        
        private string diskFolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DiskFolder {
            get {
                return this.diskFolderField;
            }
            set {
                this.diskFolderField = value;
                this.RaisePropertyChanged("DiskFolder");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dmsdox.com/")]
    public partial class Document : Divider {
        
        private string fileNameField;
        
        private int pagesField;
        
        private int currentPageField;
        
        private string subDocsField;
        
        private string extNameField;
        
        private int boxNumberField;
        
        private System.DateTime archivedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("Pages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CurrentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("CurrentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubDocs {
            get {
                return this.subDocsField;
            }
            set {
                this.subDocsField = value;
                this.RaisePropertyChanged("SubDocs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExtName {
            get {
                return this.extNameField;
            }
            set {
                this.extNameField = value;
                this.RaisePropertyChanged("ExtName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int BoxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                this.boxNumberField = value;
                this.RaisePropertyChanged("BoxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime ArchivedDate {
            get {
                return this.archivedDateField;
            }
            set {
                this.archivedDateField = value;
                this.RaisePropertyChanged("ArchivedDate");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://www.dmsdox.com/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dmsdox.com/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dmsdox.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dmsdox.com/", Order=2)]
        public string name;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(string token, byte[] data, string name) {
            this.token = token;
            this.data = data;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://www.dmsdox.com/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dmsdox.com/", Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : DNSTester.DOXAPI.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<DNSTester.DOXAPI.ServiceSoap>, DNSTester.DOXAPI.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string userName, string password, string environment) {
            return base.Channel.Login(userName, password, environment);
        }
        
        public DNSTester.DOXAPI.DocType[] GetAllDocTypes(string token) {
            return base.Channel.GetAllDocTypes(token);
        }
        
        public DNSTester.DOXAPI.Document GetDocument(string token, DNSTester.DOXAPI.Document docToSearch) {
            return base.Channel.GetDocument(token, docToSearch);
        }
        
        public DNSTester.DOXAPI.TreeItemWithDocType GetTreeItemWithDocType(string token, DNSTester.DOXAPI.TreeItemWithDocType itemToSearch) {
            return base.Channel.GetTreeItemWithDocType(token, itemToSearch);
        }
        
        public string UpdateTreeItemWithDocType(string token, DNSTester.DOXAPI.TreeItemWithDocType updateItem) {
            return base.Channel.UpdateTreeItemWithDocType(token, updateItem);
        }
        
        public string DeleteDocument(string token, long id) {
            return base.Channel.DeleteDocument(token, id);
        }
        
        public string Archive(string token, DNSTester.DOXAPI.Document doc, DNSTester.DOXAPI.Binder binder, string dividerPath, bool ocr) {
            return base.Channel.Archive(token, doc, binder, dividerPath, ocr);
        }
        
        public DNSTester.DOXAPI.TreeItemWithDocType[] FindTreeItemWithDocType(string token, DNSTester.DOXAPI.SearchField[] searchFields, long docTypeId) {
            return base.Channel.FindTreeItemWithDocType(token, searchFields, docTypeId);
        }
        
        public DNSTester.DOXAPI.DocType GetDocType(string token, long id) {
            return base.Channel.GetDocType(token, id);
        }
        
        public string CreateBinder(string token, DNSTester.DOXAPI.Binder binder, string parentBranch, DNSTester.DOXAPI.DividerSet dividerSet) {
            return base.Channel.CreateBinder(token, binder, parentBranch, dividerSet);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DNSTester.DOXAPI.UploadFileResponse DNSTester.DOXAPI.ServiceSoap.UploadFile(DNSTester.DOXAPI.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(string token, byte[] data, string name) {
            DNSTester.DOXAPI.UploadFileRequest inValue = new DNSTester.DOXAPI.UploadFileRequest();
            inValue.token = token;
            inValue.data = data;
            inValue.name = name;
            DNSTester.DOXAPI.UploadFileResponse retVal = ((DNSTester.DOXAPI.ServiceSoap)(this)).UploadFile(inValue);
            return retVal.UploadFileResult;
        }
        
        public string test() {
            return base.Channel.test();
        }
        
        public string[] LoggenInUsers() {
            return base.Channel.LoggenInUsers();
        }
        
        public string[] GetBarCodes(string token, string fileName) {
            return base.Channel.GetBarCodes(token, fileName);
        }
        
        public string[] QuickBarCode(string fileName) {
            return base.Channel.QuickBarCode(fileName);
        }
        
        public string GetDocumentURL(string token, long id) {
            return base.Channel.GetDocumentURL(token, id);
        }
        
        public string GetQueryURL(string token, DNSTester.DOXAPI.SearchField[] searchFields, long docTypeId) {
            return base.Channel.GetQueryURL(token, searchFields, docTypeId);
        }
    }
}
