//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InvoiceXML {
    
    private InvoiceXMLEnvelope envelopeField;
    
    /// <remarks/>
    public InvoiceXMLEnvelope Envelope {
        get {
            return this.envelopeField;
        }
        set {
            this.envelopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceXMLEnvelope {
    
    private string senderField;
    
    private string receiverField;
    
    private System.DateTime messageDateField;
    
    private System.DateTime messageTimeField;
    
    private InvoiceXMLEnvelopeHeader headerField;
    
    private InvoiceXMLEnvelopeLine[] detailsField;
    
    /// <remarks/>
    public string Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public string Receiver {
        get {
            return this.receiverField;
        }
        set {
            this.receiverField = value;
        }
    }
    
    /// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    //public System.DateTime MessageDate
    //{
    //    get
    //    {
    //        return this.messageDateField;
    //    }
    //    set
    //    {
    //        this.messageDateField = value;
    //    }
    //}
    public string MessageDate
    {
        get
        {
            return  System.String.Format("{0:yyyy-MM-dd}", this.messageDateField);
        }
        set
        {
            this.messageDateField = System.DateTime.Parse(value); ;
        }
    }
    
    /// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public string MessageTime
    {
        get
        {
            return System.String.Format("{0:HH:mm:ss}", this.messageTimeField);
        }
        set
        {
            this.messageTimeField = System.DateTime.Parse(value);
        }
    }
    
    /// <remarks/>
    public InvoiceXMLEnvelopeHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Line", IsNullable=false)]
    public InvoiceXMLEnvelopeLine[] Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceXMLEnvelopeHeader {
    
    private string invoiceTypeField;
    
    private string invoiceNoField;
    
    private string invoiceDateField;
    
    private string supplierNameField;
    
    private string discountAmountField;
    
    private string companyCodeField;
    
    private string exchangeRateField;
    
    private string currencyField;
    
    private InvoiceXMLEnvelopeHeaderTaxInvoice taxInvoiceField;
    
    private InvoiceXMLEnvelopeHeaderDocInvoiceType docInvoiceTypeField;
    
    private string supplierPrivateCompanyCodeField;
    
    private string retailerPrivateCompanyCodeField;
    
    private string currencyDocSumField;
    
    private decimal lineSumField;
    
    private decimal docSumField;
    
    private decimal taxSumField;

    private string taxSumNISField;

    private string currencyRateField; 

    private string numOfLinesField;
    
    private decimal taxRateField;
    
    private string deliveryField;
    
    private InvoiceXMLEnvelopeHeaderReference[] referenceField;
    
    private string companyNameField;
    
    private string addressField;
    
    private string cityField;
    
    private string stateField;
    
    private string countryField;
    
    private string pOBField;
    
    private string zipcodeField;
    
    private string paymentTermsField;
    
    private string bankField;
    
    private string accountField;
    
    private string sNAttachNameField;
    
    /// <remarks/>
    public string InvoiceType {
        get {
            return this.invoiceTypeField;
        }
        set {
            this.invoiceTypeField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierName {
        get {
            return this.supplierNameField;
        }
        set {
            this.supplierNameField = value;
        }
    }
    
    /// <remarks/>
    public string DiscountAmount {
        get {
            return this.discountAmountField;
        }
        set {
            this.discountAmountField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyCode {
        get {
            return this.companyCodeField;
        }
        set {
            this.companyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ExchangeRate {
        get {
            return this.exchangeRateField;
        }
        set {
            this.exchangeRateField = value;
        }
    }
    
    /// <remarks/>
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceXMLEnvelopeHeaderTaxInvoice TaxInvoice {
        get {
            return this.taxInvoiceField;
        }
        set {
            this.taxInvoiceField = value;
        }
    }
    
    /// <remarks/>
    public InvoiceXMLEnvelopeHeaderDocInvoiceType DocInvoiceType {
        get {
            return this.docInvoiceTypeField;
        }
        set {
            this.docInvoiceTypeField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierPrivateCompanyCode {
        get {
            return this.supplierPrivateCompanyCodeField;
        }
        set {
            this.supplierPrivateCompanyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string RetailerPrivateCompanyCode {
        get {
            return this.retailerPrivateCompanyCodeField;
        }
        set {
            this.retailerPrivateCompanyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyDocSum {
        get {
            return this.currencyDocSumField;
        }
        set {
            this.currencyDocSumField = value;
        }
    }
    
    /// <remarks/>
    public decimal LineSum {
        get {
            return this.lineSumField;
        }
        set {
            this.lineSumField = value;
        }
    }
    
    /// <remarks/>
    public decimal DocSum {
        get {
            return this.docSumField;
        }
        set {
            this.docSumField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxSum {
        get {
            return this.taxSumField;
        }
        set {
            this.taxSumField = value;
        }
    }
    /// <remarks/>
    public string TaxSumNIS
    {
        get
        {
            return this.taxSumNISField;
        }
        set
        {
            this.taxSumNISField = value;
        }
    }
    /// <remarks/>
    public string CurrencyRate
    {
        get
        {
            return this.currencyRateField;
        }
        set
        {
            this.currencyRateField = value;
        }
    } 
    /// <remarks/>
    public string NumOfLines {
        get {
            return this.numOfLinesField;
        }
        set {
            this.numOfLinesField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxRate {
        get {
            return this.taxRateField;
        }
        set {
            this.taxRateField = value;
        }
    }
    
    /// <remarks/>
    public string Delivery {
        get {
            return this.deliveryField;
        }
        set {
            this.deliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public InvoiceXMLEnvelopeHeaderReference[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string POB {
        get {
            return this.pOBField;
        }
        set {
            this.pOBField = value;
        }
    }
    
    /// <remarks/>
    public string Zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentTerms {
        get {
            return this.paymentTermsField;
        }
        set {
            this.paymentTermsField = value;
        }
    }
    
    /// <remarks/>
    public string Bank {
        get {
            return this.bankField;
        }
        set {
            this.bankField = value;
        }
    }
    
    /// <remarks/>
    public string Account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    public string SNAttachName {
        get {
            return this.sNAttachNameField;
        }
        set {
            this.sNAttachNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InvoiceXMLEnvelopeHeaderTaxInvoice {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("חשבונית מס")]
    חשבוניתמס,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Tax Invoice")]
    TaxInvoice,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InvoiceXMLEnvelopeHeaderDocInvoiceType {
    
    /// <remarks/>
    מקור,
    
    /// <remarks/>
    העתק,
    
    /// <remarks/>
    Copy,
    
    /// <remarks/>
    Original,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceXMLEnvelopeHeaderReference {
    
    private InvoiceXMLEnvelopeHeaderReferenceRefType refTypeField;
    
    private string refNoField;
    
    private string refDateField;
    
    /// <remarks/>
    public InvoiceXMLEnvelopeHeaderReferenceRefType RefType {
        get {
            return this.refTypeField;
        }
        set {
            this.refTypeField = value;
        }
    }
    
    /// <remarks/>
    public string RefNo {
        get {
            return this.refNoField;
        }
        set {
            this.refNoField = value;
        }
    }
    
    /// <remarks/>
    public string RefDate {
        get {
            return this.refDateField;
        }
        set {
            this.refDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InvoiceXMLEnvelopeHeaderReferenceRefType {
    
    /// <remarks/>
    entry,
    shipment,
    /// <remarks/>
    purchaseOrder,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceXMLEnvelopeLine {
    
    private string lineNoField;
    
    private string itemBarcodeField;

    private string CustomerBarcodeField;
    
    private string unitsQtyField;
    
    private string itemPriceBrutoField;
    
    private string lineSumField;
    
    private string itemDescriptionField;
    
    private string partNumberField;
    
    private InvoiceXMLEnvelopeLineReference[] referenceField;
    
    /// <remarks/>
    public string LineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    public string ItemBarcode {
        get {
            return this.itemBarcodeField;
        }
        set {
            this.itemBarcodeField = value;
        }
    }
    /// <remarks/>
    public string CustomerBarcode
    {
        get
        {
            return this.CustomerBarcodeField;
        }
        set
        {
            this.CustomerBarcodeField = value;
        }
    }
    
    /// <remarks/>
    public string UnitsQty {
        get {
            return this.unitsQtyField;
        }
        set {
            this.unitsQtyField = value;
        }
    }
    
    /// <remarks/>
    public string ItemPriceBruto {
        get {
            return this.itemPriceBrutoField;
        }
        set {
            this.itemPriceBrutoField = value;
        }
    }
    
    /// <remarks/>
    public string LineSum {
        get {
            return this.lineSumField;
        }
        set {
            this.lineSumField = value;
        }
    }
    
    /// <remarks/>
    public string ItemDescription {
        get {
            return this.itemDescriptionField;
        }
        set {
            this.itemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string PartNumber {
        get {
            return this.partNumberField;
        }
        set {
            this.partNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public InvoiceXMLEnvelopeLineReference[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InvoiceXMLEnvelopeLineReference {
    
    private InvoiceXMLEnvelopeLineReferenceRefType refTypeField;
    
    private string refNoField;
    
    private string refDateField;
    
    /// <remarks/>
    public InvoiceXMLEnvelopeLineReferenceRefType RefType {
        get {
            return this.refTypeField;
        }
        set {
            this.refTypeField = value;
        }
    }
    
    /// <remarks/>
    public string RefNo {
        get {
            return this.refNoField;
        }
        set {
            this.refNoField = value;
        }
    }
    
    /// <remarks/>
    public string RefDate {
        get {
            return this.refDateField;
        }
        set {
            this.refDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum InvoiceXMLEnvelopeLineReferenceRefType {
    
    /// <remarks/>
    entry,
    shipment,
    /// <remarks/>
    purchaseOrder,
}
