//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PackingSlipXML {
    
    private PackingSlipXMLEnvelope envelopeField;
    
    /// <remarks/>
    public PackingSlipXMLEnvelope Envelope {
        get {
            return this.envelopeField;
        }
        set {
            this.envelopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackingSlipXMLEnvelope {
    
    private string senderField;
    
    private string receiverField;
    
    private PackingSlipXMLEnvelopeHeader headerField;
    
    private PackingSlipXMLEnvelopeLine[] detailsField;
    
    /// <remarks/>
    public string Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public string Receiver {
        get {
            return this.receiverField;
        }
        set {
            this.receiverField = value;
        }
    }
    
    /// <remarks/>
    public PackingSlipXMLEnvelopeHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Line", IsNullable=false)]
    public PackingSlipXMLEnvelopeLine[] Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackingSlipXMLEnvelopeHeader {
    
    private string packingSlipNoField;
    
    private string packingSlipDateField;
    
    private string deliveryDateField;
    
    private string supplierNameField;
    
    private string companyNameField;
    
    private string addressField;
    
    private string cityField;
    
    private string countryField;
    
    private string sNAttachNameField;
    
    private PackingSlipXMLEnvelopeHeaderReference[] referenceField;
    
    /// <remarks/>
    public string PackingSlipNo {
        get {
            return this.packingSlipNoField;
        }
        set {
            this.packingSlipNoField = value;
        }
    }
    
    /// <remarks/>
    public string PackingSlipDate {
        get {
            return this.packingSlipDateField;
        }
        set {
            this.packingSlipDateField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierName {
        get {
            return this.supplierNameField;
        }
        set {
            this.supplierNameField = value;
        }
    }
    
    /// <remarks/>
    public string CompanyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string SNAttachName {
        get {
            return this.sNAttachNameField;
        }
        set {
            this.sNAttachNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public PackingSlipXMLEnvelopeHeaderReference[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackingSlipXMLEnvelopeHeaderReference {
    
    private PackingSlipXMLEnvelopeHeaderReferenceRefType refTypeField;
    
    private string refNoField;
    
    private string refDateField;
    
    /// <remarks/>
    public PackingSlipXMLEnvelopeHeaderReferenceRefType RefType {
        get {
            return this.refTypeField;
        }
        set {
            this.refTypeField = value;
        }
    }
    
    /// <remarks/>
    public string RefNo {
        get {
            return this.refNoField;
        }
        set {
            this.refNoField = value;
        }
    }
    
    /// <remarks/>
    public string RefDate {
        get {
            return this.refDateField;
        }
        set {
            this.refDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum PackingSlipXMLEnvelopeHeaderReferenceRefType {
    
    /// <remarks/>
    entry,
    
    /// <remarks/>
    purchaseOrder,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackingSlipXMLEnvelopeLine {
    
    private string lineNoField;
    
    private string supplierLineNoField;
    
    private string itemBarcodeField;
    
    private string customerBarcodeField;
    
    private string unitsQtyField;
    
    private string unitsQtyMeaField;
    
    private string itemDescriptionField;
    
    private string customerItemDescriptionField;
    
    private string commentsField;
    
    private string revisionField;
    
    private PackingSlipXMLEnvelopeLineReference[] referenceField;
    
    /// <remarks/>
    public string LineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierLineNo {
        get {
            return this.supplierLineNoField;
        }
        set {
            this.supplierLineNoField = value;
        }
    }
    
    /// <remarks/>
    public string ItemBarcode {
        get {
            return this.itemBarcodeField;
        }
        set {
            this.itemBarcodeField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerBarcode {
        get {
            return this.customerBarcodeField;
        }
        set {
            this.customerBarcodeField = value;
        }
    }
    
    /// <remarks/>
    public string UnitsQty {
        get {
            return this.unitsQtyField;
        }
        set {
            this.unitsQtyField = value;
        }
    }
    
    /// <remarks/>
    public string UnitsQtyMea {
        get {
            return this.unitsQtyMeaField;
        }
        set {
            this.unitsQtyMeaField = value;
        }
    }
    
    /// <remarks/>
    public string ItemDescription {
        get {
            return this.itemDescriptionField;
        }
        set {
            this.itemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerItemDescription {
        get {
            return this.customerItemDescriptionField;
        }
        set {
            this.customerItemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public string Revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference")]
    public PackingSlipXMLEnvelopeLineReference[] Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PackingSlipXMLEnvelopeLineReference {
    
    private PackingSlipXMLEnvelopeLineReferenceRefType refTypeField;
    
    private string refNoField;
    
    private string supplierRefNoField;
    
    private string refDateField;
    
    /// <remarks/>
    public PackingSlipXMLEnvelopeLineReferenceRefType RefType {
        get {
            return this.refTypeField;
        }
        set {
            this.refTypeField = value;
        }
    }
    
    /// <remarks/>
    public string RefNo {
        get {
            return this.refNoField;
        }
        set {
            this.refNoField = value;
        }
    }
    
    /// <remarks/>
    public string SupplierRefNo {
        get {
            return this.supplierRefNoField;
        }
        set {
            this.supplierRefNoField = value;
        }
    }
    
    /// <remarks/>
    public string RefDate {
        get {
            return this.refDateField;
        }
        set {
            this.refDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum PackingSlipXMLEnvelopeLineReferenceRefType {
    
    /// <remarks/>
    entry,
    
    /// <remarks/>
    purchaseOrder,
}
