//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deliveryNoteService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlexAutoArchiving\\PackingSlips\\NewPackingSlips")]
        public string NewPackingSlipPath {
            get {
                return ((string)(this["NewPackingSlipPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mignt002\\Public\\PackingSlipsLog\\{ccc}\\in")]
        public string BAANLog {
            get {
                return ((string)(this["BAANLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select t_item,t_ddat,t_orno from baandb.ttdsls045{0} where t_dino={1}")]
        public string ItemsQuery {
            get {
                return ((string)(this["ItemsQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select t_refa from baandb.ttdsls040{0} where t_orno={1}")]
        public string CustomerOrderQuery {
            get {
                return ((string)(this["CustomerOrderQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BarcodeDebugFile {
            get {
                return ((string)(this["BarcodeDebugFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mignt080\\public\\DoxArchive\\scaner\\envFlex\\5")]
        public string DefectedQueuePath {
            get {
                return ((string)(this["DefectedQueuePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\NewInvoices")]
        public string NewInvoicePath {
            get {
                return ((string)(this["NewInvoicePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlexAutoArchiving\\InvoiceLog")]
        public string InvoiceLogPath {
            get {
                return ((string)(this["InvoiceLogPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select distinct com001.t_emno, com001.t_nama, com001.t_telp, com971.t_code from baandb.ttccom971{0} as com971, baandb.ttccom001{0} as com001 where com971.t_emno=com001.t_emno and com971.t_citg in (Select t_citg from baandb.ttcmcs023{0} where t_cuno='{1}') and com971.t_code in ('CTR','PMR')")]
        public string CustomerPeopleQuery {
            get {
                return ((string)(this["CustomerPeopleQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flex")]
        public string DoxEnv {
            get {
                return ((string)(this["DoxEnv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlexAutoArchiving\\PackingSlips\\PackingSlipError")]
        public string PSErrorQueue {
            get {
                return ((string)(this["PSErrorQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://+:80/dashboard/")]
        public string HTTPPrefix {
            get {
                return ((string)(this["HTTPPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DSN=BAAN")]
        public string BAANDB {
            get {
                return ((string)(this["BAANDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mignt002\\storenext\\XML_Out")]
        public string StorenextXMLLandingFolder {
            get {
                return ((string)(this["StorenextXMLLandingFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mignt002\\storenext\\PDF_Out")]
        public string StorenextPDFLandingFolder {
            get {
                return ((string)(this["StorenextPDFLandingFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableStorenextIntegration {
            get {
                return ((bool)(this["EnableStorenextIntegration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\mignt002\\public\\jobs\\Sale_Invoice_Storenext.txt")]
        public string StorenextRanFile {
            get {
                return ((string)(this["StorenextRanFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlexAutoArchiving\\IntegrationQueue")]
        public string IntegrationQueue {
            get {
                return ((string)(this["IntegrationQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/04/2012 02:00:00")]
        public global::System.DateTime IntegrationWakeUpTime {
            get {
                return ((global::System.DateTime)(this["IntegrationWakeUpTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y:\\\\DMSMRB\\\\To Baan\\\\{ccc}\\\\in")]
        public string BAANOrd99Log {
            get {
                return ((string)(this["BAANOrd99Log"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select t_nama, t_namc, t_refs, t_telp, t_seak from baandb.ttccom020{0} where t_su" +
            "no=\'{1}\'")]
        public string SuppliersQuery {
            get {
                return ((string)(this["SuppliersQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select ttccom040{0}.t_email from baandb.ttccom040{0} where  ttccom040{0}.t_suno=\'" +
            "{1}\' and ttccom040{0}.t_code=11 and ttccom040{0}.t_actv=11")]
        public string SuppliersEmailsQuery {
            get {
                return ((string)(this["SuppliersEmailsQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Program Files\\\\DMS Inc\\\\DeliverNotesSetup_Test\\\\a")]
        public string NewOrder99Path {
            get {
                return ((string)(this["NewOrder99Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Program Files\\\\DMS Inc\\\\DeliverNotesSetup_Test\\\\t")]
        public string NewOrder99ReturnedDocumentPath {
            get {
                return ((string)(this["NewOrder99ReturnedDocumentPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Program Files\\\\DMS Inc\\\\DeliverNotesSetup_Test\\\\EmptyOrd99Document.pdf")]
        public string Ord99EmptyPDFDocument {
            get {
                return ((string)(this["Ord99EmptyPDFDocument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Projects\\\\FlexAutoArchiving\\\\InvoiceForStorenext\\\\")]
        public string StoreNextPath {
            get {
                return ((string)(this["StoreNextPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select suno from baandb.ttcom811{0} where snum=\'{1}\'")]
        public string GetFlexStorenextSuppliersQuery {
            get {
                return ((string)(this["GetFlexStorenextSuppliersQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Projects\\\\FlexAutoArchiving\\\\SupplierInvoiceError")]
        public string SupplierInvoiceErrorQueue {
            get {
                return ((string)(this["SupplierInvoiceErrorQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Program Files\\\\DMS Inc\\\\DeliverNotesSetup_Test\\\\s")]
        public string StorenextSuppInvDocPath {
            get {
                return ((string)(this["StorenextSuppInvDocPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y:\\PackingSlipsBarcode\\doc")]
        public string psXmlPath {
            get {
                return ((string)(this["psXmlPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xml_Out")]
        public string psXmlOutPath {
            get {
                return ((string)(this["psXmlOutPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF_Received")]
        public string psPdfReceivedPath {
            get {
                return ((string)(this["psPdfReceivedPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERROR")]
        public string psPdfErrOutPath {
            get {
                return ((string)(this["psPdfErrOutPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Projects\\\\FlexAutoArchiving\\\\PackingSlips\\\\NewPackingSlipsMIG")]
        public string NewPackingSlipMIGPath {
            get {
                return ((string)(this["NewPackingSlipMIGPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF_Signed")]
        public string psSignedPath {
            get {
                return ((string)(this["psSignedPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\PsCheckedWithBarcodes\\\\")]
        public string CheckedPackingSlipMIGPath {
            get {
                return ((string)(this["CheckedPackingSlipMIGPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string NumOfArchive {
            get {
                return ((string)(this["NumOfArchive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\PsChecked\\\\")]
        public string CheckedPackingSlipMIGWithoutBPath {
            get {
                return ((string)(this["CheckedPackingSlipMIGWithoutBPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF_Out")]
        public string psPdfOutPath {
            get {
                return ((string)(this["psPdfOutPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\\Projects\\FlexAutoArchiving\\PackingSlips\\NewPackingSlipsMIG</string>
  <string>C:\\Projects\\FlexAutoArchiving\\PackingSlips\\NewPackingSlips</string>
  <string>\\\\mignt002\\public\\PackingSlipsBarcode\\doc\\400\\PDF_Received</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PSPathes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PSPathes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\10.229.8.14\\\\PackingSlips\\\\NewPackingSlipsMIG")]
        public string ShipmentsDir {
            get {
                return ((string)(this["ShipmentsDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\mignt080\\\\media\\\\DoxArchive\\\\scaner\\\\envFlex\\\\MachsanErrors")]
        public string MachsanErrors {
            get {
                return ((string)(this["MachsanErrors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\\\\mignt002\\storenext\\DOXTemp\\DOX\\Invoice\\splitsPdf</string>
  <string>\\\\mignt002\\storenext\\DOXTemp\\DOX\\COC\\splitsPdf</string>
  <string>\\\\mignt002\\storenext\\DOXTemp\\DOX\\Delivery note\\splitsPdf</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReturnFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReturnFiles"]));
            }
        }
    }
}
